CREATE DATABASE IF NOT EXISTS `file` /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin */;
USE `file`;

CREATE TABLE IF NOT EXISTS `file` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  PRIMARY KEY (`id`)
);